### ISSUE TITLE
Mocking properties added to requests by middleware

### ISSUE THREAD

**Issue by hasRandy** [i-like-robots/express-request-mock#7]
I have some middleware that adds a `context` object to each request (user information, request id for tracking, etc) as a separate property `req.context`. I occasionally will need to test router behavior related to values in that context object. At the moment, it looks like there is no way to enhance the `req` object that will be passed to the router when calling `requestMock(...)`.

What are your thoughts on adding support for transforming the request object before the route handler is invoked?  Or, if that seems like a bad idea, do you have any alternate suggestions?

**Comment by i-like-robots** [comment]
I think it's quite common for middleware to attach properties to the request or response object so yes, this seems reasonable.

Do you have any thoughts about how this should be exposed?

**Comment by schottra** [comment]
A few things spring to mind as possibilities:
1. Allow passing of additional properties in the `options` object, maybe one for `req` and one for `res`, and then attach those using `Object.assign` after the objects are created by the underlying `createRequest`. It's pretty simple to implement, and pretty simple to use, but it lacks in flexibility and doesn't quite mimic the pattern used by middleware.
2. Add optional `requestTransformer` and `responseTransformer` properties to the `options` hash. They are simple transform functions that will receive the corresponding objects after they are created and have the ability to modify them before they are passed along to the calling code. `createRequest` should ignore them, since they aren't properties supported by that API. This is more in line with the middleware pattern. But it has the downside of polluting the object passed to `createRequest`. So if they ever _did_ start strictly enforcing properties, this library would break.
3. Same as #2, but accept the transformers in an object that is passed as an optional third argument.

**Comment by i-like-robots** [comment]
2 and 3 I think sound good... the provided function arguments could be simple mocks or the real thing depending on the context... though I think the latter could lead to complication (I don't think it's useful to add support for async or proper fallthrough behaviour, that should be left for the middleware test itself).
